//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ocell.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ocell.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocell is a open source (ASL) twitter client for Windows Phone, developed by Guillermo Julián. You can follow @OcellApp on Twitter to receive the lastest updates about Ocell..
        /// </summary>
        public static string AboutP1 {
            get {
                return ResourceManager.GetString("AboutP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backgrounds credit: Thanks to Paul Phönixweiß (Egg), Dimitar Karaytchev (Diamond), Lauren (Floral), Sam Feyaerts (Map) and Wilmotte Bastien (Tire) for making their patterns available on subtlepattern.com..
        /// </summary>
        public static string AboutP2 {
            get {
                return ResourceManager.GetString("AboutP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About tweet scheduling....
        /// </summary>
        public static string AboutScheduling {
            get {
                return ResourceManager.GetString("AboutScheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Because of the system&apos;s limitations, we can only check your scheduled tweets every half hour, so it&apos;s possible that your tweet will not be sent at the exact time you specified. Also, remember that if you have your phone in battery saving mode or turned off, we won&apos;t be able to send your tweet..
        /// </summary>
        public static string AboutSchedulingMessage {
            get {
                return ResourceManager.GetString("AboutSchedulingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account protected!.
        /// </summary>
        public static string AccountProtected {
            get {
                return ResourceManager.GetString("AccountProtected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accounts.
        /// </summary>
        public static string AccountsPivot {
            get {
                return ResourceManager.GetString("AccountsPivot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account unprotected!.
        /// </summary>
        public static string AccountUnprotected {
            get {
                return ResourceManager.GetString("AccountUnprotected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add account.
        /// </summary>
        public static string AddAccount {
            get {
                return ResourceManager.GetString("AddAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add column.
        /// </summary>
        public static string AddColumn {
            get {
                return ResourceManager.GetString("AddColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{0} has been added to the list {1}..
        /// </summary>
        public static string AddedToList {
            get {
                return ResourceManager.GetString("AddedToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add favorite.
        /// </summary>
        public static string AddFavorite {
            get {
                return ResourceManager.GetString("AddFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add image.
        /// </summary>
        public static string AddImage {
            get {
                return ResourceManager.GetString("AddImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a minute ago.
        /// </summary>
        public static string AMinuteAgo {
            get {
                return ResourceManager.GetString("AMinuteAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an hour ago.
        /// </summary>
        public static string AnHourAgo {
            get {
                return ResourceManager.GetString("AnHourAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AnotherString {
            get {
                return ResourceManager.GetString("AnotherString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a second ago.
        /// </summary>
        public static string ASecondAgo {
            get {
                return ResourceManager.GetString("ASecondAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you grant Ocell access to your location? This will enable tweet geotagging and localized Trending Topics..
        /// </summary>
        public static string AskAccessGrantGeolocation {
            get {
                return ResourceManager.GetString("AskAccessGrantGeolocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the account @{0}?.
        /// </summary>
        public static string AskAccountDelete {
            get {
                return ResourceManager.GetString("AskAccountDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to add the column {0} to the main page?.
        /// </summary>
        public static string AskAddColumn {
            get {
                return ResourceManager.GetString("AskAddColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops, it seems that this feature is only available in the full version of Ocell Pro. Click OK if you want to purchase it. Thanks!.
        /// </summary>
        public static string AskBuyFullVersion {
            get {
                return ResourceManager.GetString("AskBuyFullVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this draft?.
        /// </summary>
        public static string AskDeleteDraft {
            get {
                return ResourceManager.GetString("AskDeleteDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to enable push notifications in Ocell?.
        /// </summary>
        public static string AskEnablePush {
            get {
                return ResourceManager.GetString("AskEnablePush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this filter?.
        /// </summary>
        public static string AskFilterDelete {
            get {
                return ResourceManager.GetString("AskFilterDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask me.
        /// </summary>
        public static string AskPosition {
            get {
                return ResourceManager.GetString("AskPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to tweet from the protected account @{0}?.
        /// </summary>
        public static string AskTweetProtectedAccount {
            get {
                return ResourceManager.GetString("AskTweetProtectedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As this message is more than 140 characters long, we will use Twitlonger to send it. Do you agree?.
        /// </summary>
        public static string AskTwitlonger {
            get {
                return ResourceManager.GetString("AskTwitlonger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticating....
        /// </summary>
        public static string Authenticating {
            get {
                return ResourceManager.GetString("Authenticating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to available locations.
        /// </summary>
        public static string AvailableLocations {
            get {
                return ResourceManager.GetString("AvailableLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The background will change when you restart the application..
        /// </summary>
        public static string BackgroundChangeOnRestart {
            get {
                return ResourceManager.GetString("BackgroundChangeOnRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to backgrounds.
        /// </summary>
        public static string Backgrounds {
            get {
                return ResourceManager.GetString("Backgrounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backgrounds.
        /// </summary>
        public static string Backgrounds_CapitalFirst {
            get {
                return ResourceManager.GetString("Backgrounds_CapitalFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big.
        /// </summary>
        public static string Big {
            get {
                return ResourceManager.GetString("Big", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to block.
        /// </summary>
        public static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to block and report spam.
        /// </summary>
        public static string BlockAndReport {
            get {
                return ResourceManager.GetString("BlockAndReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tweet sent to Buffer!.
        /// </summary>
        public static string BufferUpdateSent {
            get {
                return ResourceManager.GetString("BufferUpdateSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        public static string ButtonGo {
            get {
                return ResourceManager.GetString("ButtonGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change avatar.
        /// </summary>
        public static string ChangeAvatar {
            get {
                return ResourceManager.GetString("ChangeAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will be able to change this setting anytime in the Settings page..
        /// </summary>
        public static string ChangeGeolocSetting {
            get {
                return ResourceManager.GetString("ChangeGeolocSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t validate your code. Ensure you&apos;re connected to Internet and that the code is correctly copied..
        /// </summary>
        public static string CodeInvalid {
            get {
                return ResourceManager.GetString("CodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This code is valid. Congratulations, you have unlocked Ocell Pro! Enjoy!.
        /// </summary>
        public static string CodeValid {
            get {
                return ResourceManager.GetString("CodeValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column added..
        /// </summary>
        public static string ColumnAdded {
            get {
                return ResourceManager.GetString("ColumnAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This column is already pinned..
        /// </summary>
        public static string ColumnAlreadyPinned {
            get {
                return ResourceManager.GetString("ColumnAlreadyPinned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to columns.
        /// </summary>
        public static string Columns {
            get {
                return ResourceManager.GetString("Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to compose.
        /// </summary>
        public static string Compose {
            get {
                return ResourceManager.GetString("Compose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compose tile.
        /// </summary>
        public static string ComposeTile {
            get {
                return ResourceManager.GetString("ComposeTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        public static string Contains {
            get {
                return ResourceManager.GetString("Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to conversation.
        /// </summary>
        public static string Conversation {
            get {
                return ResourceManager.GetString("Conversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversation.
        /// </summary>
        public static string Conversation_CapitalFirst {
            get {
                return ResourceManager.GetString("Conversation_CapitalFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copy hashtag.
        /// </summary>
        public static string CopyHashtag {
            get {
                return ResourceManager.GetString("CopyHashtag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copy link.
        /// </summary>
        public static string CopyLink {
            get {
                return ResourceManager.GetString("CopyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copy user name.
        /// </summary>
        public static string CopyUsername {
            get {
                return ResourceManager.GetString("CopyUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core.
        /// </summary>
        public static string Core {
            get {
                return ResourceManager.GetString("Core", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t block @{0}..
        /// </summary>
        public static string CouldntBlock {
            get {
                return ResourceManager.GetString("CouldntBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t find that user..
        /// </summary>
        public static string CouldntFindUser {
            get {
                return ResourceManager.GetString("CouldntFindUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t not follow @{0}..
        /// </summary>
        public static string CouldntFollow {
            get {
                return ResourceManager.GetString("CouldntFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t get your relationship with this user..
        /// </summary>
        public static string CouldntGetRelationship {
            get {
                return ResourceManager.GetString("CouldntGetRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t load this filter..
        /// </summary>
        public static string CouldntLoadFilter {
            get {
                return ResourceManager.GetString("CouldntLoadFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t report @{0}..
        /// </summary>
        public static string CouldntReport {
            get {
                return ResourceManager.GetString("CouldntReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t unblock @{0}..
        /// </summary>
        public static string CouldntUnblock {
            get {
                return ResourceManager.GetString("CouldntUnblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t not unfollow @{0}..
        /// </summary>
        public static string CouldntUnfollow {
            get {
                return ResourceManager.GetString("CouldntUnfollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeem codes.
        /// </summary>
        public static string CouponCodes {
            get {
                return ResourceManager.GetString("CouponCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create filter.
        /// </summary>
        public static string CreateFilter {
            get {
                return ResourceManager.GetString("CreateFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create list.
        /// </summary>
        public static string CreateList {
            get {
                return ResourceManager.GetString("CreateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new list.
        /// </summary>
        public static string CreateNewList {
            get {
                return ResourceManager.GetString("CreateNewList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials for {0} saved..
        /// </summary>
        public static string CredentialsSaved {
            get {
                return ResourceManager.GetString("CredentialsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete tweet.
        /// </summary>
        public static string DeleteTweet {
            get {
                return ResourceManager.GetString("DeleteTweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deny.
        /// </summary>
        public static string Deny {
            get {
                return ResourceManager.GetString("Deny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Messages.
        /// </summary>
        public static string DirectMessages {
            get {
                return ResourceManager.GetString("DirectMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disable quick column add.
        /// </summary>
        public static string DisableQuickAdd {
            get {
                return ResourceManager.GetString("DisableQuickAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not contain.
        /// </summary>
        public static string DoesNotContain {
            get {
                return ResourceManager.GetString("DoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t show tweets where.
        /// </summary>
        public static string DontShowTweetsWhere {
            get {
                return ResourceManager.GetString("DontShowTweetsWhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to downloading followers....
        /// </summary>
        public static string DownloadingFollowers {
            get {
                return ResourceManager.GetString("DownloadingFollowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to downloading following....
        /// </summary>
        public static string DownloadingFollowing {
            get {
                return ResourceManager.GetString("DownloadingFollowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to downloading image....
        /// </summary>
        public static string DownloadingImage {
            get {
                return ResourceManager.GetString("DownloadingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to downloading trending topics....
        /// </summary>
        public static string DownloadingTopics {
            get {
                return ResourceManager.GetString("DownloadingTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to downloading list of users....
        /// </summary>
        public static string DownloadingUserList {
            get {
                return ResourceManager.GetString("DownloadingUserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft deleted..
        /// </summary>
        public static string DraftDeleted {
            get {
                return ResourceManager.GetString("DraftDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drafts.
        /// </summary>
        public static string Drafts {
            get {
                return ResourceManager.GetString("Drafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft saved!.
        /// </summary>
        public static string DraftSaved {
            get {
                return ResourceManager.GetString("DraftSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit muted tweets.
        /// </summary>
        public static string EditMutedTweets {
            get {
                return ResourceManager.GetString("EditMutedTweets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 hours.
        /// </summary>
        public static string EightHours {
            get {
                return ResourceManager.GetString("EightHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enable quick column add.
        /// </summary>
        public static string EnableQuickAdd {
            get {
                return ResourceManager.GetString("EnableQuickAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your search query:.
        /// </summary>
        public static string EnterQuery {
            get {
                return ResourceManager.GetString("EnterQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error happened while trying to get auth URL. Ensure that the time on your phone is correct, and try changing the network (Wifi or mobile). Please contact @OcellApp if this happens frequently..
        /// </summary>
        public static string ErrorAuthURL {
            get {
                return ResourceManager.GetString("ErrorAuthURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving Buffer profiles..
        /// </summary>
        public static string ErrorBufferProfiles {
            get {
                return ResourceManager.GetString("ErrorBufferProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error happened while trying to get client tokens. Try again, and please contact @OcellApp if this happens frequently..
        /// </summary>
        public static string ErrorClientTokens {
            get {
                return ResourceManager.GetString("ErrorClientTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating Buffer update..
        /// </summary>
        public static string ErrorCreatingBuffer {
            get {
                return ResourceManager.GetString("ErrorCreatingBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating this list.
        /// </summary>
        public static string ErrorCreatingList {
            get {
                return ResourceManager.GetString("ErrorCreatingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has happened while trying to create the Twitlonger post..
        /// </summary>
        public static string ErrorCreatingTwitlonger {
            get {
                return ResourceManager.GetString("ErrorCreatingTwitlonger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t delete this tweet..
        /// </summary>
        public static string ErrorDeletingTweet {
            get {
                return ResourceManager.GetString("ErrorDeletingTweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t download the image..
        /// </summary>
        public static string ErrorDownloadingImage {
            get {
                return ResourceManager.GetString("ErrorDownloadingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t download your saved searches..
        /// </summary>
        public static string ErrorDownloadingSearches {
            get {
                return ResourceManager.GetString("ErrorDownloadingSearches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred trying to download the user list..
        /// </summary>
        public static string ErrorDownloadingUsers {
            get {
                return ResourceManager.GetString("ErrorDownloadingUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That tweet is duplicated..
        /// </summary>
        public static string ErrorDuplicateTweet {
            get {
                return ResourceManager.GetString("ErrorDuplicateTweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t get the full user profile..
        /// </summary>
        public static string ErrorGettingProfile {
            get {
                return ResourceManager.GetString("ErrorGettingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading lists.
        /// </summary>
        public static string ErrorLoadingLists {
            get {
                return ResourceManager.GetString("ErrorLoadingLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading Trending Topics..
        /// </summary>
        public static string ErrorLoadingTT {
            get {
                return ResourceManager.GetString("ErrorLoadingTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading the tweet..
        /// </summary>
        public static string ErrorLoadingTweet {
            get {
                return ResourceManager.GetString("ErrorLoadingTweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading the tweets: {0}.
        /// </summary>
        public static string ErrorLoadingTweets {
            get {
                return ResourceManager.GetString("ErrorLoadingTweets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred..
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s no selected account..
        /// </summary>
        public static string ErrorNoAccount {
            get {
                return ResourceManager.GetString("ErrorNoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error report.
        /// </summary>
        public static string ErrorReport {
            get {
                return ResourceManager.GetString("ErrorReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred the last time you ran this application. Would you like to send an email to report it? The report contains data to help me correct the bug. It will not send any personal data..
        /// </summary>
        public static string ErrorReportMessage {
            get {
                return ResourceManager.GetString("ErrorReportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving this filter..
        /// </summary>
        public static string ErrorSavingFilter {
            get {
                return ResourceManager.GetString("ErrorSavingFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred saving this item for later..
        /// </summary>
        public static string ErrorSavingLater {
            get {
                return ResourceManager.GetString("ErrorSavingLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error uploading the image. Please try again..
        /// </summary>
        public static string ErrorUploadingImage {
            get {
                return ResourceManager.GetString("ErrorUploadingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error happened while uploading your image. Verify the file is less than 700 kB of size..
        /// </summary>
        public static string ErrorUploadingProfileImage {
            get {
                return ResourceManager.GetString("ErrorUploadingProfileImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favorite.
        /// </summary>
        public static string Favorite {
            get {
                return ResourceManager.GetString("Favorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favorited!.
        /// </summary>
        public static string Favorited {
            get {
                return ResourceManager.GetString("Favorited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filter this column.
        /// </summary>
        public static string FilterColumn {
            get {
                return ResourceManager.GetString("FilterColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filtered!.
        /// </summary>
        public static string Filtered {
            get {
                return ResourceManager.GetString("Filtered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filters.
        /// </summary>
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to follow.
        /// </summary>
        public static string Follow {
            get {
                return ResourceManager.GetString("Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to followers.
        /// </summary>
        public static string Followers {
            get {
                return ResourceManager.GetString("Followers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to following.
        /// </summary>
        public static string Following {
            get {
                return ResourceManager.GetString("Following", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to follow @OcellApp on Twitter to receive updates?.
        /// </summary>
        public static string FollowOcellAppMessage {
            get {
                return ResourceManager.GetString("FollowOcellAppMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size:.
        /// </summary>
        public static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forever.
        /// </summary>
        public static string Forever {
            get {
                return ResourceManager.GetString("Forever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for {0}.
        /// </summary>
        public static string ForX {
            get {
                return ResourceManager.GetString("ForX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From:.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geolocation.
        /// </summary>
        public static string Geolocation {
            get {
                return ResourceManager.GetString("Geolocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable geolocalization.
        /// </summary>
        public static string Geotagging {
            get {
                return ResourceManager.GetString("Geotagging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to global.
        /// </summary>
        public static string Global {
            get {
                return ResourceManager.GetString("Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to go to user....
        /// </summary>
        public static string GoToUser {
            get {
                return ResourceManager.GetString("GoToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hashtags.
        /// </summary>
        public static string Hashtags {
            get {
                return ResourceManager.GetString("Hashtags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hashtag(s) {0} are muted until {1}..
        /// </summary>
        public static string HashtagsMutedUntil {
            get {
                return ResourceManager.GetString("HashtagsMutedUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0} credentials.
        /// </summary>
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is member of the following lists:.
        /// </summary>
        public static string IsMemberOfLists {
            get {
                return ResourceManager.GetString("IsMemberOfLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last month.
        /// </summary>
        public static string LastMonth {
            get {
                return ResourceManager.GetString("LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last year.
        /// </summary>
        public static string LastYear {
            get {
                return ResourceManager.GetString("LastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List created!.
        /// </summary>
        public static string ListCreated {
            get {
                return ResourceManager.GetString("ListCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems that the list {0} has been deleted on Twitter. If you want to delete it from Ocell, go to &quot;columns&quot; and long-press it to delete..
        /// </summary>
        public static string ListDeleted {
            get {
                return ResourceManager.GetString("ListDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists.
        /// </summary>
        public static string Lists {
            get {
                return ResourceManager.GetString("Lists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading lists....
        /// </summary>
        public static string LoadingLists {
            get {
                return ResourceManager.GetString("LoadingLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load more....
        /// </summary>
        public static string LoadMore {
            get {
                return ResourceManager.GetString("LoadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login:.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manage lists.
        /// </summary>
        public static string ManageLists {
            get {
                return ResourceManager.GetString("ManageLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add/remove from lists....
        /// </summary>
        public static string ManageListsForUser {
            get {
                return ResourceManager.GetString("ManageListsForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentions.
        /// </summary>
        public static string Mentions {
            get {
                return ResourceManager.GetString("Mentions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message scheduled!.
        /// </summary>
        public static string MessageScheduled {
            get {
                return ResourceManager.GetString("MessageScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mute....
        /// </summary>
        public static string Mute {
            get {
                return ResourceManager.GetString("Mute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mute tweets with this domain.
        /// </summary>
        public static string MuteDomain {
            get {
                return ResourceManager.GetString("MuteDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muted until {0}..
        /// </summary>
        public static string MutedUntil {
            get {
                return ResourceManager.GetString("MutedUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mute hashtag.
        /// </summary>
        public static string MuteHashtag {
            get {
                return ResourceManager.GetString("MuteHashtag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mute user.
        /// </summary>
        public static string MuteUser {
            get {
                return ResourceManager.GetString("MuteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my profile.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{0} mentioned you.
        /// </summary>
        public static string NewMention {
            get {
                return ResourceManager.GetString("NewMention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new mentions.
        /// </summary>
        public static string NewMentions {
            get {
                return ResourceManager.GetString("NewMentions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new mentions and messages.
        /// </summary>
        public static string NewMentionsMessages {
            get {
                return ResourceManager.GetString("NewMentionsMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{0} sent you a message.
        /// </summary>
        public static string NewMessage {
            get {
                return ResourceManager.GetString("NewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new messages.
        /// </summary>
        public static string NewMessages {
            get {
                return ResourceManager.GetString("NewMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New tweet.
        /// </summary>
        public static string NewTweet {
            get {
                return ResourceManager.GetString("NewTweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} new mentions.
        /// </summary>
        public static string NewXMentions {
            get {
                return ResourceManager.GetString("NewXMentions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} new mentions and messages.
        /// </summary>
        public static string NewXMentionsMessages {
            get {
                return ResourceManager.GetString("NewXMentionsMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} new messages.
        /// </summary>
        public static string NewXMessages {
            get {
                return ResourceManager.GetString("NewXMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seems that you haven&apos;t configured any Buffer account. Do you want to do it now?.
        /// </summary>
        public static string NoBufferConfigured {
            get {
                return ResourceManager.GetString("NoBufferConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have a Buffer profile for any of the Twitter accounts configured with Ocell..
        /// </summary>
        public static string NoBufferProfilesAdded {
            get {
                return ResourceManager.GetString("NoBufferProfilesAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hashtags to mute..
        /// </summary>
        public static string NoHashtagsToMute {
            get {
                return ResourceManager.GetString("NoHashtagsToMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new notifications..
        /// </summary>
        public static string NoNewNotifications {
            get {
                return ResourceManager.GetString("NoNewNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify mentions:.
        /// </summary>
        public static string NotifyMentions {
            get {
                return ResourceManager.GetString("NotifyMentions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify messages:.
        /// </summary>
        public static string NotifyMessages {
            get {
                return ResourceManager.GetString("NotifyMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s not a valid resource.
        /// </summary>
        public static string NotValidResource {
            get {
                return ResourceManager.GetString("NotValidResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a valid URL..
        /// </summary>
        public static string NotValidURL {
            get {
                return ResourceManager.GetString("NotValidURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now you follow @{0}..
        /// </summary>
        public static string NowYouFollow {
            get {
                return ResourceManager.GetString("NowYouFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve unfollowed @{0}..
        /// </summary>
        public static string NowYouUnfollow {
            get {
                return ResourceManager.GetString("NowYouUnfollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 day.
        /// </summary>
        public static string OneDay {
            get {
                return ResourceManager.GetString("OneDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour.
        /// </summary>
        public static string OneHour {
            get {
                return ResourceManager.GetString("OneHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 week.
        /// </summary>
        public static string OneWeek {
            get {
                return ResourceManager.GetString("OneWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnlyTile.
        /// </summary>
        public static string OnlyTile {
            get {
                return ResourceManager.GetString("OnlyTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password (if you have one):.
        /// </summary>
        public static string PasswordIfYouHave {
            get {
                return ResourceManager.GetString("PasswordIfYouHave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pictures.
        /// </summary>
        public static string Pictures {
            get {
                return ResourceManager.GetString("Pictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin this column to start.
        /// </summary>
        public static string PinColumnStart {
            get {
                return ResourceManager.GetString("PinColumnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin compose tile to start.
        /// </summary>
        public static string PinComposeToStart {
            get {
                return ResourceManager.GetString("PinComposeToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin to main page.
        /// </summary>
        public static string PinToMainPage {
            get {
                return ResourceManager.GetString("PinToMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin to start.
        /// </summary>
        public static string PinToStart {
            get {
                return ResourceManager.GetString("PinToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        public static string Privacy_Policy {
            get {
                return ResourceManager.GetString("Privacy_Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy: Ocell will not save your localization in any register or file in your phone. Ocell will not send your location to any Internet server, except to Twitter.com and for the purposes exposed above (tweet geotagging and localization of Trending Topics)..
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string Private {
            get {
                return ResourceManager.GetString("Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile image has been changed..
        /// </summary>
        public static string ProfileImageChanged {
            get {
                return ResourceManager.GetString("ProfileImageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to protect.
        /// </summary>
        public static string Protect {
            get {
                return ResourceManager.GetString("Protect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        public static string Public {
            get {
                return ResourceManager.GetString("Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push notifications.
        /// </summary>
        public static string PushEnabled {
            get {
                return ResourceManager.GetString("PushEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quick view.
        /// </summary>
        public static string QuickView {
            get {
                return ResourceManager.GetString("QuickView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woops! You have spent the limit of calls to Twitter. You&apos;ll have to wait until {0}.
        /// </summary>
        public static string RateLimitHit {
            get {
                return ResourceManager.GetString("RateLimitHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to read later.
        /// </summary>
        public static string ReadLater {
            get {
                return ResourceManager.GetString("ReadLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resume last reading position?.
        /// </summary>
        public static string RecoverReadPosition {
            get {
                return ResourceManager.GetString("RecoverReadPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{0} was removed from the list {1}..
        /// </summary>
        public static string RemovedFromList {
            get {
                return ResourceManager.GetString("RemovedFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove favorite.
        /// </summary>
        public static string RemoveFavorite {
            get {
                return ResourceManager.GetString("RemoveFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        public static string Repeat {
            get {
                return ResourceManager.GetString("Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reply.
        /// </summary>
        public static string Reply {
            get {
                return ResourceManager.GetString("Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reply all.
        /// </summary>
        public static string ReplyAll {
            get {
                return ResourceManager.GetString("ReplyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have succesfully reported and blocked @{0}..
        /// </summary>
        public static string ReportedAndBlocked {
            get {
                return ResourceManager.GetString("ReportedAndBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retrieving user....
        /// </summary>
        public static string RetrievingUser {
            get {
                return ResourceManager.GetString("RetrievingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retweet.
        /// </summary>
        public static string Retweet {
            get {
                return ResourceManager.GetString("Retweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (RT by @{0}).
        /// </summary>
        public static string RetweetBy {
            get {
                return ResourceManager.GetString("RetweetBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retweeted.
        /// </summary>
        public static string Retweeted {
            get {
                return ResourceManager.GetString("Retweeted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retweet with comments.
        /// </summary>
        public static string RetweetWithComments {
            get {
                return ResourceManager.GetString("RetweetWithComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RT by .
        /// </summary>
        public static string RTBy {
            get {
                return ResourceManager.GetString("RTBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save credentials.
        /// </summary>
        public static string SaveCredentials {
            get {
                return ResourceManager.GetString("SaveCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved for later!.
        /// </summary>
        public static string SavedForLater {
            get {
                return ResourceManager.GetString("SavedForLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save draft.
        /// </summary>
        public static string SaveDraft {
            get {
                return ResourceManager.GetString("SaveDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save preferences.
        /// </summary>
        public static string SavePreferences {
            get {
                return ResourceManager.GetString("SavePreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to saving for later....
        /// </summary>
        public static string SavingForLater {
            get {
                return ResourceManager.GetString("SavingForLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to schedule.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled?.
        /// </summary>
        public static string ScheduledQuestion {
            get {
                return ResourceManager.GetString("ScheduledQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error scheduling the tweet for {0}..
        /// </summary>
        public static string ScheduleError {
            get {
                return ResourceManager.GetString("ScheduleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search_CapitalFirst {
            get {
                return ResourceManager.GetString("Search_CapitalFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search column added to main page.
        /// </summary>
        public static string SearchColumnAdded {
            get {
                return ResourceManager.GetString("SearchColumnAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one account.
        /// </summary>
        public static string SelectAccount {
            get {
                return ResourceManager.GetString("SelectAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a date and time to schedule the tweet..
        /// </summary>
        public static string SelectDateTimeToSchedule {
            get {
                return ResourceManager.GetString("SelectDateTimeToSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send dm.
        /// </summary>
        public static string SendDM {
            get {
                return ResourceManager.GetString("SendDM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sending tweet....
        /// </summary>
        public static string SendingTweet {
            get {
                return ResourceManager.GetString("SendingTweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send message.
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send to Buffer.
        /// </summary>
        public static string SendWithBuffer {
            get {
                return ResourceManager.GetString("SendWithBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set custom background.
        /// </summary>
        public static string SetCustomBackground {
            get {
                return ResourceManager.GetString("SetCustomBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share....
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show global trending topics....
        /// </summary>
        public static string ShowGlobalTopics {
            get {
                return ResourceManager.GetString("ShowGlobalTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue where I left.
        /// </summary>
        public static string ShowLastTweet {
            get {
                return ResourceManager.GetString("ShowLastTweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &quot;Resume reading&quot; button.
        /// </summary>
        public static string ShowResumeButton {
            get {
                return ResourceManager.GetString("ShowResumeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show retweets as mentions.
        /// </summary>
        public static string ShowRetweetsAsMentions {
            get {
                return ResourceManager.GetString("ShowRetweetsAsMentions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silence time when muting tweets:.
        /// </summary>
        public static string SilenceTime {
            get {
                return ResourceManager.GetString("SilenceTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        public static string Small {
            get {
                return ResourceManager.GetString("Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source {0} is muted until {1}..
        /// </summary>
        public static string SourceMutedUntil {
            get {
                return ResourceManager.GetString("SourceMutedUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap a filter to modify it, tap and hold to delete it..
        /// </summary>
        public static string TapFilter {
            get {
                return ResourceManager.GetString("TapFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add or remove the user from a list, just tap that list..
        /// </summary>
        public static string TapList {
            get {
                return ResourceManager.GetString("TapList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap a filter to modify it, tap and hold to delete..
        /// </summary>
        public static string TapToModify {
            get {
                return ResourceManager.GetString("TapToModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiles.
        /// </summary>
        public static string Tiles {
            get {
                return ResourceManager.GetString("Tiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To:.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add column tiles, go to the main page and press &quot;pin column to start&quot; in the bottom bar..
        /// </summary>
        public static string ToAddColumnTiles {
            get {
                return ResourceManager.GetString("ToAddColumnTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toast and Tile.
        /// </summary>
        public static string ToastAndTile {
            get {
                return ResourceManager.GetString("ToastAndTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the last tweet.
        /// </summary>
        public static string ToNewTweets {
            get {
                return ResourceManager.GetString("ToNewTweets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trending.
        /// </summary>
        public static string Trending {
            get {
                return ResourceManager.GetString("Trending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trending topics.
        /// </summary>
        public static string TrendingTopics {
            get {
                return ResourceManager.GetString("TrendingTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tweet deleted! (Note that it could take a few minutes to disappear completely from your streams).
        /// </summary>
        public static string TweetDeleted {
            get {
                return ResourceManager.GetString("TweetDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tweet from @{0}.
        /// </summary>
        public static string TweetFrom {
            get {
                return ResourceManager.GetString("TweetFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tweets.
        /// </summary>
        public static string Tweets {
            get {
                return ResourceManager.GetString("Tweets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tweets to load per request.
        /// </summary>
        public static string TweetsPerRequest {
            get {
                return ResourceManager.GetString("TweetsPerRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tweet text.
        /// </summary>
        public static string TweetText {
            get {
                return ResourceManager.GetString("TweetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unblock.
        /// </summary>
        public static string Unblock {
            get {
                return ResourceManager.GetString("Unblock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unfavorited!.
        /// </summary>
        public static string Unfavorited {
            get {
                return ResourceManager.GetString("Unfavorited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unfollow.
        /// </summary>
        public static string Unfollow {
            get {
                return ResourceManager.GetString("Unfollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string UnknownValue {
            get {
                return ResourceManager.GetString("UnknownValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unprotect.
        /// </summary>
        public static string Unprotect {
            get {
                return ResourceManager.GetString("Unprotect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Until.
        /// </summary>
        public static string Until {
            get {
                return ResourceManager.GetString("Until", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to until {0}..
        /// </summary>
        public static string UntilDate {
            get {
                return ResourceManager.GetString("UntilDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update column tiles in the background.
        /// </summary>
        public static string UpdateTilesInBackground {
            get {
                return ResourceManager.GetString("UpdateTilesInBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uploading picture....
        /// </summary>
        public static string UploadingPicture {
            get {
                return ResourceManager.GetString("UploadingPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sending to Twitlonger....
        /// </summary>
        public static string UploadingTwitlonger {
            get {
                return ResourceManager.GetString("UploadingTwitlonger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user {0} is muted until {1}..
        /// </summary>
        public static string UserIsMutedUntil {
            get {
                return ResourceManager.GetString("UserIsMutedUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{0} is now blocked..
        /// </summary>
        public static string UserIsNowBlocked {
            get {
                return ResourceManager.GetString("UserIsNowBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{0} is now unblocked..
        /// </summary>
        public static string UserIsNowUnblocked {
            get {
                return ResourceManager.GetString("UserIsNowUnblocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or email:.
        /// </summary>
        public static string UserOrMail {
            get {
                return ResourceManager.GetString("UserOrMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User succesfully pinned..
        /// </summary>
        public static string UserPinned {
            get {
                return ResourceManager.GetString("UserPinned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users who retweeted.
        /// </summary>
        public static string UsersWhoRetweeted {
            get {
                return ResourceManager.GetString("UsersWhoRetweeted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        public static string Validate {
            get {
                return ResourceManager.GetString("Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verifying credentials....
        /// </summary>
        public static string VerifyingCredentials {
            get {
                return ResourceManager.GetString("VerifyingCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to via.
        /// </summary>
        public static string Via {
            get {
                return ResourceManager.GetString("Via", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want to mute?.
        /// </summary>
        public static string WhatToMute {
            get {
                return ResourceManager.GetString("WhatToMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the app starts....
        /// </summary>
        public static string WhenAppStart {
            get {
                return ResourceManager.GetString("WhenAppStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days ago.
        /// </summary>
        public static string XDaysAgo {
            get {
                return ResourceManager.GetString("XDaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} follows you.
        /// </summary>
        public static string XFollowsY {
            get {
                return ResourceManager.GetString("XFollowsY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours ago.
        /// </summary>
        public static string XHoursAgo {
            get {
                return ResourceManager.GetString("XHoursAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes ago.
        /// </summary>
        public static string XMinutesAgo {
            get {
                return ResourceManager.GetString("XMinutesAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} months ago.
        /// </summary>
        public static string XMonthsAgo {
            get {
                return ResourceManager.GetString("XMonthsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not follow you.
        /// </summary>
        public static string XNotFollowsY {
            get {
                return ResourceManager.GetString("XNotFollowsY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seconds ago.
        /// </summary>
        public static string XSecondsAgo {
            get {
                return ResourceManager.GetString("XSecondsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} years ago.
        /// </summary>
        public static string XYearsAgo {
            get {
                return ResourceManager.GetString("XYearsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yesterday.
        /// </summary>
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to log in with Twitter in order to use Ocell..
        /// </summary>
        public static string YouHaveToLogin {
            get {
                return ResourceManager.GetString("YouHaveToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your lists.
        /// </summary>
        public static string YourLists {
            get {
                return ResourceManager.GetString("YourLists", resourceCulture);
            }
        }
    }
}
